### model
# model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct-AWQ
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
# deepspeed: examples/deepspeed/ds_z3_config.json 

### dataset
# dataset: mllm_demo,identity,alpaca_en_demo  # video: mllm_video_demo
# dataset: r2r_train,identity,alpaca_en_demo  # video: mllm_video_demo
# dataset: r2r_train_320_7
# dataset: r2r_train_240_10
dataset: r2r_train_240_5
template: qwen2_vl
# cutoff_len: 2048
# 参考：https://github.com/hiyouga/LLaMA-Factory/issues/6844
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
# preprocessing_num_workers: 16
preprocessing_num_workers: 64
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_vl-3b/lora/sft
logging_steps: 10
# save_steps: 500
save_steps: 40
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
# gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 20.0
# num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
# bf16: true
bf16: false
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
