### model
# model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct-AWQ
# model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
model_name_or_path: /LLM-VLM/train_saves/Qwen2.5-VL-3b-424-240-9-r2r-fulldatasets-more-stop-0804/outputs-4642
# image_max_pixels: 262144
image_max_pixels: 101800
# video_max_pixels: 16384
video_max_pixels: 384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

# deepspeed fei offload
# deepspeed: examples/deepspeed/ds_z3_config.json 

# kaiqi offload
deepspeed: examples/deepspeed/ds_z3_offload_config.json 

# use_unsloth

### dataset
# dataset: mllm_demo,identity,alpaca_en_demo  # video: mllm_video_demo
# dataset: r2r_train,identity,alpaca_en_demo  # video: mllm_video_demo
# dataset: r2r_train_320_7
# dataset: r2r_train_240_10
# dataset: r2r_train_240_5
# dataset: r2r_train_424_240_9
dataset: r2r_train_424_240_9_more_stop_1p6
template: qwen2_vl
cutoff_len: 2048
# 参考：https://github.com/hiyouga/LLaMA-Factory/issues/6844
# cutoff_len: 4096
# max_samples: 1000
max_samples: 500000  #334259
overwrite_cache: true
# preprocessing_num_workers: 16
preprocessing_num_workers: 32
dataloader_num_workers: 4
# 保存预处理数据集，能省很多时间
tokenized_path: saves/qwen2_vl-3b/dataset/sft

### output
output_dir: saves/qwen2_vl-3b/lora/sft
logging_steps: 10
# save_steps: 500
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 3
gradient_accumulation_steps: 8
# gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 1
# num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
# bf16: true
bf16: false
fp16: true

ddp_timeout: 180000000
resume_from_checkpoint: null

gradient_checkpointing: true
freeze_vision_tower : true

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

# streaming: true
# accelerator_config:
  # dispatch_batches: false