### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
reward_model: saves/qwen2_vl-3b/lora/reward
image_max_pixels: 101800
video_max_pixels: 384
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

# deepspeed fei offload
# deepspeed: examples/deepspeed/ds_z3_config.json 

### dataset
# dataset: identity,alpaca_en_demo
dataset: r2r_sample
template: qwen2_vl
cutoff_len: 2048
max_samples: 500000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
# 保存预处理数据集，能省很多时间
# tokenized_path: saves/qwen2_vl-3b/dataset/sft

### output
output_dir: saves/qwen2_vl-3b/lora/ppo
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
# bf16: true
bf16: false
fp16: true

ddp_timeout: 180000000

gradient_checkpointing: true
freeze_vision_tower : true

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
